[package]
name = "autotex"
version = "1.1.0"
authors = ["Sungbae Jeong <almagest0328@gmail.com>"]
edition = "2018"

[dependencies]
walkdir = "2.3"
dirs = "4.0"
signal-hook = "0.3"
yaml-rust = "0.4"
clap = "3"

