[package]
name = "autotex"
version = "0.2.1"
authors = ["Sungbae Jeong <almagest0328@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2.3.1"
dirs = "3.0.0"
signal = "0.7.0"
yaml-rust = "0.4.4"
